### PR TITLE
Fix API, add Particle and ESP8266 support.

### PR DESCRIPTION
**Pull request by vshymanskyy**
* Updated API for clean, object-oriented inctremental CRC update
* Increased portability
* Added Particle and ESP8266 support
* Updated example

### CODE REVIEW

**Comment by bakercp** [comment]
Hi @vshymanskyy these changes are appreciated thanks!  Your design improvements make a lot of sense.  My only concern is that removing several static api functions is not backward compatible. Could we add the missing static api functions back and properly deprecate them for a release cycle before removing them completely (e.g. https://stackoverflow.com/questions/295120/c-mark-as-deprecated)?  That said, overall this is a big improvement, so I'm open to discussion!

**Comment by vshymanskyy** [comment]
Ok, check this version
I run both old and new examples to see it it calculates correctly after API merge.

**Comment by bakercp** [comment]
Super thanks!

**Comment by bakercp** [comment]
@vshymanskyy I just pushed an updated release and cleaned up the example.  Could you test the latest release?

**Pull request merged**
